version: "3"
services:
  postgres:
    build:
      context: database
    ports:
      - "5432:5432"
  web:
    build:
      context: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
