version: "3"
services:
  postgres:
    build:
      context: database
    ports:
      - "5432:5432"
  web:
    build:
      context: backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
  frontend:
    build:
      context: frontend
    depends_on:
      - web
    command: npm start
    volumes:
      - ./frontend/src:/usr/src/app/my-app/src
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - web
