version: "3"
services:
  postgres:
    build:
      context: database
    ports:
      - "5432:5432"
  web:
    build:
      context: backend
    # volumes:
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    depends_on:
      - web
    command: npm start
# add volume mounts for each service so that the code is mounted into the container
    volumes:
      - ./frontend/src:/usr/src/app/my-app/src